---

- name: Enable borgbackup timer
  ansible.builtin.systemd:
    name: "ansible-borgbackup-{{ borgbackup_vars.name }}.timer"
    state: started
    enabled: true

- name: Daemon reload
  ansible.builtin.systemd:
    daemon_reload: true
